kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/service-b
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
        # This expands to [<space>.s.]service-a.<guid>.<region>.aksapp.io
        - $(spacePrefix)service-a$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
      dockerfile: Dockerfile.develop
    container:
      command:  [dotnet, run, -c, "${Configuration:-Debug}", --no-restore, --no-build, --no-launch-profile, "--"]
      sync:
      - "**/Pages/**"
      - "**/Views/**"
      - "**/wwwroot/**"
      - "!**/*.{sln,csproj}"
      refresh:
        processesToKill: [dotnet, vsdbg]
        buildCommands:
        - [dotnet, build, -c, "${Configuration:-Debug}", --no-restore]
