FROM microsoft/aspnetcore-build:2
# This is auto-injected by Mindaro as a volume mount
# Temporarily included to enable local Docker experience
RUN apt-get update \
 && apt-get install -y --no-install-recommends unzip \
 && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build

CMD ["dotnet", "run"]