FROM microsoft/aspnetcore-build:2
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 80

WORKDIR /src
COPY service-b.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build

CMD ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile"]